package com.equationl.wxsteplog.util.datastore

object DataKey {
    const val LOG_USER_MODE = "LOG_USER_MODE"
    const val LOG_MULTIPLE_USER_NAME = "LOG_MULTIPLE_USER_NAME"
    const val LOG_INTERVAL_TIME = "LOG_INTERVAL_TIME"
    const val LOG_IS_INTERVAL_TIME_RANDOM_RANGE = "LOG_IS_INTERVAL_TIME_RANDOM_RANGE"
    const val LOG_INTERVAL_TIME_RANDOM_RANGE = "LOG_INTERVAL_TIME_RANDOM_RANGE"
    const val LOG_IS_ALL_WITH_SPECIAL_USER = "LOG_IS_ALL_WITH_SPECIAL_USER"
    const val SHOW_DATA_FILTER_USER = "SHOW_DATA_FILTER_USER"
    const val WX_PKG_NAME = "WX_PKG_NAME"
    const val WX_LAUNCHER_PKG_NAME = "WX_LAUNCHER_PKG_NAME"
}