package com.equationl.common.datastore

object DataKey {
    const val LOG_USER_MODE = "LOG_USER_MODE"
    const val LOG_MULTIPLE_USER_NAME = "LOG_MULTIPLE_USER_NAME"
    const val LOG_INTERVAL_TIME = "LOG_INTERVAL_TIME"
    const val LOG_IS_INTERVAL_TIME_RANDOM_RANGE = "LOG_IS_INTERVAL_TIME_RANDOM_RANGE"
    const val LOG_INTERVAL_TIME_RANDOM_RANGE = "LOG_INTERVAL_TIME_RANDOM_RANGE"
    const val LOG_IS_ALL_WITH_SPECIAL_USER = "LOG_IS_ALL_WITH_SPECIAL_USER"
    const val SHOW_DATA_FILTER_USER = "SHOW_DATA_FILTER_USER"
    const val WX_PKG_NAME = "WX_PKG_NAME"
    const val WX_LAUNCHER_PKG_NAME = "WX_LAUNCHER_PKG_NAME"
    const val RUN_STEP_INTERVAL_TIME = "RUN_STEP_INTERVAL_TIME"
    const val SHOW_DETAIL_LOG = "SHOW_DETAIL_LOG"
    const val CSV_DELIMITER = "CSV_DELIMITER"
    const val WX_VIEW_LIMIT = "WX_VIEW_LIMIT"
    const val STEP_ORDER_VIEW_LIMIT = "ORDER_VIEW_LIMIT"
    const val IS_AUTO_RUNNING = "IS_AUTO_RUNNING"
    const val IS_AUTO_RESET = "IS_AUTO_RESET"
    const val REST_TIME = "REST_TIME"
}