name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: '发布的标签名称 (例如: v1.0.0)'
        required: true
        type: string

# 添加权限配置
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          dir
          echo "Gradle version:"
          ./gradlew --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Release
        run: |
          ./gradlew build
        env:
          GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=1g"

      - name: Sign app APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          files: app/build/outputs/apk/release/*-signed.apk
      
